const $=x=>document.getElementById(x),F=["prospect_name","policy_id","customer_id","customer_country","global_country","sales_manager","broker","broker_contact","offer_deadline","precheck","key_account_underwriter","prospect_remarks","status","insurable_turnover","premium_rate","expected_premium","premium_principle"];let R=[],S=null,on=false;
const n=v=>Number(String(v??0).replace(/\s/g,"").replace(",",".").replace(/[^0-9.\-]/g,""))||0,fmt=v=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(n(v)).replace(/,/g," "),rate=v=>n(String(v).replace("%","")),days=d=>d?Math.ceil((new Date(d+"T00:00:00")-new Date(new Date().toDateString()))/86400000):null,esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
async function init(){try{S=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);let x=await S.from("prospects").select("*");if(x.error)throw x.error;R=x.data;on=true;$("mode").textContent="Shared online database"}catch(e){console.warn(e);R=JSON.parse(localStorage.gpm||"[]");$("mode").textContent="Local demo mode"}opts();render();table()}
function opts(){let u=k=>[...new Set(R.map(x=>x[k]).filter(Boolean))].sort(),set=(id,a,label)=>{$(id).innerHTML=`<option value="">${label}</option>`+a.map(x=>`<option>${esc(x)}</option>`).join("")};set("df",u("customer_country"),"All countries");set("sf",u("status"),"All statuses");$("countriesList").innerHTML=u("customer_country").map(x=>`<option value="${esc(x)}">`).join("");$("managersList").innerHTML=u("sales_manager").map(x=>`<option value="${esc(x)}">`).join("");$("brokersList").innerHTML=u("broker").map(x=>`<option value="${esc(x)}">`).join("")}
function filtered(){return R.filter(r=>(!$("df").value||r.customer_country===$("df").value)&&(!$("sf").value||r.status===$("sf").value))}
function render(){let a=filtered();$("total").textContent=a.length;$("open").textContent=a.filter(x=>x.status==="Open").length;$("won").textContent=a.filter(x=>x.status==="Won").length;$("overdue").textContent=a.filter(x=>x.status==="Open"&&days(x.offer_deadline)<0).length;$("premium").textContent=fmt(a.reduce((s,x)=>s+n(x.expected_premium),0));let g={};a.forEach(x=>g[x.customer_country||"Not set"]=(g[x.customer_country||"Not set"]||0)+1);let mx=Math.max(1,...Object.values(g));$("countries").innerHTML=Object.entries(g).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${v/mx*100}%"></div></div><b>${v}</b></div>`).join("")}
function table(){let q=$("search").value.toLowerCase();let a=R.filter(r=>!q||Object.values(r).some(v=>String(v??"").toLowerCase().includes(q)));$("body").innerHTML=a.map(r=>`<tr><td><b>${esc(r.prospect_name)}</b></td><td>${esc(r.policy_id)}</td><td>${esc(r.customer_id)}</td><td>${esc(r.customer_country)}</td><td>${esc(r.global_country)}</td><td>${esc(r.sales_manager)}</td><td>${esc(r.broker)}</td><td>${esc(r.broker_contact)}</td><td>${esc(r.offer_deadline)}</td><td class="${days(r.offer_deadline)<0?"late":""}">${days(r.offer_deadline)??""}</td><td>${esc(r.precheck)}</td><td>${esc(r.key_account_underwriter)}</td><td class="rem">${esc(r.prospect_remarks)}</td><td>${esc(r.status)}</td><td>${fmt(r.insurable_turnover)}</td><td>${r.premium_rate?n(r.premium_rate).toFixed(3)+"%":""}</td><td>${fmt(r.expected_premium)}</td><td>${esc(r.premium_principle)}</td><td><button onclick="edit('${r.id}')">Edit</button> <button onclick="del('${r.id}')">Delete</button></td></tr>`).join("")}
function show(x){$("dash").hidden=x!=="dash";$("pros").hidden=x!=="pros"}function openForm(){$("form").reset();$("id").value="";$("status").value="Open";dlg.showModal()}function calc(){$("expected_premium").value=fmt(n($("insurable_turnover").value)*rate($("premium_rate").value)/100)}
window.edit=id=>{let r=R.find(x=>String(x.id)===String(id));F.forEach(k=>$(k).value=r[k]??"");$("id").value=id;dlg.showModal()};window.del=async id=>{if(!confirm("Delete prospect?"))return;if(on){let x=await S.from("prospects").delete().eq("id",id);if(x.error)return alert(x.error.message)}R=R.filter(x=>String(x.id)!==String(id));if(!on)localStorage.gpm=JSON.stringify(R);opts();render();table()}
$("form").onsubmit=async e=>{e.preventDefault();let r={};F.forEach(k=>r[k]=$(k).value);r.insurable_turnover=n(r.insurable_turnover);r.expected_premium=n(r.expected_premium);r.premium_rate=rate(r.premium_rate);let id=$("id").value;if(on){let x=id?await S.from("prospects").update(r).eq("id",id).select().single():await S.from("prospects").insert(r).select().single();if(x.error)return alert(x.error.message);R=id?R.map(z=>String(z.id)===String(id)?x.data:z):[x.data,...R]}else{r.id=id||crypto.randomUUID();R=id?R.map(z=>String(z.id)===String(id)?r:z):[r,...R];localStorage.gpm=JSON.stringify(R)}dlg.close();opts();render();table()}
function exportCsv(){let q=$("search").value.toLowerCase(),a=R.filter(r=>!q||Object.values(r).some(v=>String(v??"").toLowerCase().includes(q)));if(!a.length)return;let keys=F,text="\ufeff"+keys.join(";")+"\n"+a.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";")).join("\n"),b=new Blob([text],{type:"text/csv"}),z=document.createElement("a");z.href=URL.createObjectURL(b);z.download="pipeline_report.csv";z.click()}init();